version: '2'
services:
  ${MICROSERVICE}:
    image: node:${NODEVERSION}
    container_name: ${PROJECTKEY}-${SYSENV}-${MICROSERVICE}
    volumes:
      - ./containers/${PROJECTKEY}-${SYSENV}-${MICROSERVICE}/src:/src
      - ./node_modules:/src/node_modules
      - ./services/${MICROSERVICE}:/src/${MICROSERVICE}
      - ./index.js:/src/${MICROSERVICE}/index.js
      - ./translations.json:/src/${MICROSERVICE}/translations.json
      - ./sharedlib:/src/${MICROSERVICE}/sharedlib
      - ./sharedmodels:/src/${MICROSERVICE}/sharedmodels
      - ./package.json:/src/package.json
    env_file:
      - ./${SYSENV}.env
    environment:
      - SRV_NAME=${MICROSERVICE}
      - DEBUG=${DEBUG}
    links:
      - queue:queue
      - mongodb:mongodb
      # - postgresdb:postgresdb
    depends_on:
      - queue
      - mongodb
      # - postgresdb
    command: /bin/bash -c '[[ "$DEBUG" == "0" ]] && node /src/${MICROSERVICE} || sleep 360000'
    restart: 'on-failure:50'
    network_mode: "bridge"
