---
swagger: "2.0"
info:
  title: "File Upload API"
  description: |
    #### Upload:
    Upload the file/s(array of image/file) to target destination. The URLs of the uploaded files are returned.
  version: "1.0.0"
host: 'key-api-local.example.com'
basePath: /fileUpload
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  "/v1/upload":
    post:
      #override default value to accept formData
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - "Upload"
      summary: "Upload file to target destination"
      description: "Specified file is uploaded to target destination in the specified bucket"
      # parameters:
        # - name: objectType
        #   in: formData
        #   description: "Contains the file type(image/pdf)"
        #   type: string
        #   enum:
        #     - 'image'
        #     - 'pdf'
        # - name: objectPath
        #   in: formData
        #   description: "Contains the file path"
        #   type: string
        # - name: objectTarget
        #   in: formData
        #   description: "Contains the name of service to upload to"
        #   type: string
        #   enum:
        #     - 'awsS3'
        # - name: file
        #   in: formData
        #   type: file
        #   description: "The uploaded file"
        #   required: true
      responses:
        "200":
          description: "Successful"
          schema:
            $ref: "#/definitions/Response"
definitions:
  Response:
    description: "The output for successful upload."
    type: object
    properties:
      success:
        type: boolean
        description: "Whether the operation was successful or not."
      message:
        $ref: "#/definitions/Message"
      data:
        type: array
        items:
          type: string
          description: "URL of the uploaded file if successful or error message if not"
  Message:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: "The message code for the operation status."
      desc:
        type: string
        description: "The message for the operation status."
