---
swagger: "2.0"
info:
  title: "KEY Group APIs"
  version: "1.0.0"
host: 'key-local-api.example.com'
basePath: /group
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  "/v1/create":
    post:
      parameters:
        - name: createGroup
          in: body
          required: true
          schema:
            $ref: "#/definitions/createGroup"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/get":
    post:
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/update":
    post:
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/delete":
    delete:
      parameters:
        - name: deleteGroup
          in: body
          required: true
          schema:
            $ref: "#/definitions/deleteGroup"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
securityDefinitions:
  jwt.secured:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Message:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: "The message code for the operation status."
      msg:
        type: string
        description: "The message for the operation status."
  Output:
    type: object
    properties:
      success:
        type: string
        format: boolean
        description: Tell's whether action is performed succesfully or not
      message:
        $ref: '#/definitions/Message'
  Error:
    properties:
      code:
        description: "Error Code"
        format: int32
        type: integer
      message:
        description: "Error message"
        type: string
  createGroup:
    type: object
    properties:
      agentIds:
        type: array
        items:
          type: string
      description:
        type: string
      name:
        type: string
  deleteGroup:
    type: object
    properties:
      deptId:
        type: string
  addAgent:
    type: object
    properties:
      deptId:
        type: string
      agentIds:
        type: array
        items:
          type: string
  removeAgent:
    type: object
    properties:
      deptId:
        type: string
      agentIds:
        type: array
        items:
          type: string