swagger: "2.0"
info:
  title: "KEY Invitation API"
  version: "1.0.0"
host: 'key-local-api.example.com'
basePath: /invitations
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  "/v1/inviteUsers":
    post:
      parameters:
        - name: invitation
          in: body
          required: true
          schema:
            type: object
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/validateInvitation":
    post:
      parameters:
        - name: invitation
          in: body
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  jwt.secured:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Message:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: "The message code for the operation status."
      msg:
        type: string
        description: "The message for the operation status."
  Output:
    type: object
    properties:
      success:
        type: string
        format: boolean
        description: Tell's whether action is performed succesfully or not
      message:
        $ref: '#/definitions/Message'
  Error:
    properties:
      code:
        description: "Error Code"
        format: int32
        type: integer
      message:
        description: "Error message"
        type: string