swagger: "2.0"
info:
  title: "KEY API"
  version: "1.0.0"
host: 'key-local-api.example.com'
basePath: /team
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  "/v1/create":
    post:
      parameters:
        - name: createTeam
          in: body
          required: true
          schema:
            $ref: "#/definitions/createTeam"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/update":
    put:
      parameters:
        - name: updateTeam
          in: body
          required: true
          schema:
            $ref: "#/definitions/updateTeam"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/delete":
    delete:
      parameters:
        - name: deleteTeam
          in: body
          required: true
          schema:
            $ref: "#/definitions/deleteTeam"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/get":
    post:
      parameters:
        - name: getTeam
          in: body
          required: true
          schema:
            type: object
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/validate":
    post:
      parameters:
        - name: checkSubDomain
          in: body
          required: true
          schema:
            type: object
            required:
              - subDomain
            properties:
              subDomain:
                type: string
                description: "The subdomain to be checked for availability"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/checkStatus":
    post:
      parameters:
        - name: checkSubdomainSetupStatus
          in: body
          required: true
          schema:
            type: object
            properties:
              teamId:
                type: string
                description: "The Id of the team to be validated"
              subDomain:
                type: string
                description: "The sub-domain of the team to be validated"
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
  "/v1/createToken":
    post:
      parameters:
        - name: createJWTToken
          in: body
          required: true
          schema:
            type: object
      responses:
        "200":
          description: "Ok"
          schema:
            $ref: "#/definitions/Output"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      security:
        - jwt.secured: []
securityDefinitions:
  jwt.secured:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Message:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: "The message code for the operation status."
      msg:
        type: string
        description: "The message for the operation status."
  Output:
    type: object
    properties:
      success:
        type: string
        format: boolean
        description: Tells whether action is performed succesfully or not
      message:
        $ref: '#/definitions/Message'
  Error:
    properties:
      code:
        description: "Error Code"
        format: int32
        type: integer
      message:
        description: "Error message"
        type: string
  createTeam:
    type: object
    properties:
      subDomain:
        type: string
      description:
        type: string
      name:
        type: string
      website:
        type: string
  updateTeam:
    type: object
    properties:
      description:
        type: string
      name:
        type: string
      website:
        type: string
      ownerId:
        type: integer
      teamId:
        type: integer
  deleteTeam:
    type: object
    properties:
      teamId:
        type: integer
